version: 2
jobs:
  test:
    branches:
      ignore: master
    docker:
      - image: circleci/node:dubnium
    steps:
      - checkout
      - run: npm install
      - run:
          name: Test
          command: CI=true npm test
      - run:
          name: Lint
          command: npm run lint:ci
      - run:
          name: Build
          command: npm run build
  publish:
    branches:
      only: master
    docker:
      - image: circleci/node:dubnium
    environment:
      - APP_ID: kaddnceobbflkbpfmnlpoijihclphame
    steps:
      - checkout
      - run: npm install
      - run:
          name: Test
          command: CI=true npm test
      - run:
          name: Lint
          command: npm run lint:ci
      - run:
          name: Build App
          command: npm run build
      - run:
          name: Package Extension
          command: tar -zcvf ispy.zip build/
      - run:
          name: "Publish to the Google Chrome Store"
          command: |
            ACCESS_TOKEN=$(curl "https://accounts.google.com/o/oauth2/token" -d "client_id=${CLIENT_ID}&client_secret=${CLIENT_SECRET}&refresh_token=${REFRESH_TOKEN}&grant_type=refresh_token&redirect_uri=urn:ietf:wg:oauth:2.0:oob" | jq -r .access_token)
            curl -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "x-goog-api-version: 2" -X PUT -T ispy.zip -v "https://www.googleapis.com/upload/chromewebstore/v1.1/items/${APP_ID}"
            curl -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "x-goog-api-version: 2" -H "Content-Length: 0" -X POST -v "https://www.googleapis.com/chromewebstore/v1.1/items/${APP_ID}/publish"
